#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Jun  9 20:35:46 2017

@author: zhouying
"""

import tensorflow as tf
v1 = tf.Variable(tf.random_normal([1,2]), name="v1")
v2 = tf.Variable(tf.random_normal([2,3]), name="v2")
init_op = tf.global_variables_initializer()
#saver = tf.train.Saver()
with tf.Session() as sess:
    sess.run(init_op)
    print(v2.eval())