#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Jun 12 17:12:22 2017

@author: zhouying
"""
import tensorflow as tf
input1 = tf.constant(3.0)
input2 = tf.constant(2.0)
input3 = tf.constant(5.0)
intermed = tf.add(input2, input3)
mul = tf.add(input1, intermed)
with tf.Session() as sess:
  result = sess.run([mul, intermed])
  print(result)